stages:
  - check
  - deploy

check_schema:
  stage: check
  only:
    - dev
  script:
    - ssh $SSH_USER@$SSH_TEST_IP "cd electronic_library && bash scripts/check_schema.sh library.db"
    - ssh $SSH_USER@$SSH_STAGE_IP "cd electronic_library && bash scripts/check_schema.sh library.db"

deploy_stage:
  stage: deploy
  only:
    - dev
  script:
    - ssh $SSH_USER@$SSH_STAGE_IP "cd electronic_library && sqlite3 library.db < db/migrate.sql"
